### ISSUE TITLE
NumPy and Numba dependency issues

### ISSUE THREAD

**Issue by SPDA36** [shap/shap#3186]
### Issue Description

Hello,
I ran into this issue when trying to install `shap-0.42.1` which required `numpy` to be downgraded.  `numpy` was downgraded from `1.25.2-py311h0b4df5a_0 --> 1.24.4-py311h0b4df5a_0
`. After the downgrade, I could installed `shap`.  When I tried to import `shap`, then `numba` had a dependency issue which requires further downgrade of `numpy`.  `ImportError: Numba needs NumPy 1.24 or less.`  This leads to even further issues with other environment dependencies.

### Minimal Reproducible Example

```python
import shap
```

### Traceback

```shell


---> 23 import shap
     24 shap.initjs()

File ~\miniconda3\envs\\Lib\site-packages\shap\__init__.py:5
      1 # flake8: noqa
      3 __version__ = "0.42.1"
----> 5 from ._explanation import Explanation, Cohorts
      7 # explainers
      8 from .explainers._explainer import Explainer

File ~\miniconda3\envs\\Lib\site-packages\shap\_explanation.py:13
     10 import sklearn
     11 from slicer import Alias, Obj, Slicer
---> 13 from .utils._exceptions import DimensionError
     14 from .utils._general import OpChain
     16 # slicer confuses pylint...
     17 # pylint: disable=no-member

File ~\miniconda3\envs\\Lib\site-packages\shap\utils\__init__.py:1
----> 1 from ._clustering import (
      2     delta_minimization_order,
      3     hclust,
      4     hclust_ordering,
      5     partition_tree,
      6     partition_tree_shuffle,
      7 )
      8 from ._general import (
      9     OpChain,
     10     approximate_interactions,
   (...)
     20     suppress_stderr,
     21 )
     22 from ._masked_model import MaskedModel, make_masks

File ~\miniconda3\envs\\Lib\site-packages\shap\utils\_clustering.py:7
      5 import scipy.spatial
      6 import sklearn
----> 7 from numba import njit
      9 from ._general import safe_isinstance
     10 from ._show_progress import show_progress

File ~\miniconda3\envs\\Lib\site-packages\numba\__init__.py:55
     50             msg = ("Numba requires SciPy version 1.0 or greater. Got SciPy "
     51                    f"{scipy.__version__}.")
     52             raise ImportError(msg)
---> 55 _ensure_critical_deps()
     56 # END DO NOT MOVE
     57 # ---------------------- WARNING WARNING WARNING ----------------------------
     60 from ._version import get_versions

File ~\miniconda3\envs\\Lib\site-packages\numba\__init__.py:42, in _ensure_critical_deps()
     40     raise ImportError(msg)
     41 elif numpy_version > (1, 24):
---> 42     raise ImportError("Numba needs NumPy 1.24 or less")
     43 try:
     44     import scipy

ImportError: Numba needs NumPy 1.24 or less
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.42.1

**Comment by connortann** [comment]
As per my previous comment, please provide a fully reproducible example, such as the set of commands used to create a __new__ environment from scratch.

It does look like your existing environment has mutually incompatible versions of `numba` and `numpy`, which does not really seem like an issue with the shap package. Shap does not pin any versions of numba or numpy.

Have you tried creating a new environment and installing your dependencies in one command? e.g.:

```bash
# Create a new venv and activate it
python3 -m venv env
source env/bin/activate

# Install your packages
pip install numba numpy shap

# Test it
python
import shap
```

**Comment by SPDA36** [comment]
@connortann 
The environment was created with miniconda and Anaconda Navigator via the Environments tab and the create button.
`Python 3.11.4`

Packages were installed via conda prompt:
`(ds_env_AUG2023) C:\Users\admin> conda install -c conda-forge jupyterlab=4.0.4 xgboost=1.7.6 scikit-learn=1.3.0 scipy pandas=2.0.3 matplotlib=3.7.2 seaborn=0.12.2 numpy`

I did not specify a `numpy` version because I was having dependency issues with `pandas` and other packages.  So, I installed the bare minimum to try to troubleshoot for that particular issue.  That issue was solved.  `conda` decided to install `nump=1.25.2`

Then I went to install `shap`  with `conda` shortly after as it was a dependency for a notebook I was working in.  
`(ds_env_AUG2023) C:\Users\admin> conda install -c conda-forge shap=0.42.1`

`conda `decided that `numpy` needed downgraded to 1.24.4 from 1.25.2.

So, I went to load my jupyterlab notebook:
```
import numpy as np
import pandas as pd
import scipy as sp
import xgboost as xgb
from sklearn import metrics
from sklearn.model_selection import train_test_split
import shap
shap.initjs()
```
The resulting trace back:
<details>
---> 23 import shap
        24 shap.initjs()

File ~\miniconda3\envs\\Lib\site-packages\shap\__init__.py:5
      1 # flake8: noqa
      3 __version__ = "0.42.1"
----> 5 from ._explanation import Explanation, Cohorts
      7 # explainers
      8 from .explainers._explainer import Explainer

File ~\miniconda3\envs\\Lib\site-packages\shap\_explanation.py:13
     10 import sklearn
     11 from slicer import Alias, Obj, Slicer
---> 13 from .utils._exceptions import DimensionError
     14 from .utils._general import OpChain
     16 # slicer confuses pylint...
     17 # pylint: disable=no-member

File ~\miniconda3\envs\\Lib\site-packages\shap\utils\__init__.py:1
----> 1 from ._clustering import (
      2     delta_minimization_order,
      3     hclust,
      4     hclust_ordering,
      5     partition_tree,
      6     partition_tree_shuffle,
      7 )
      8 from ._general import (
      9     OpChain,
     10     approximate_interactions,
   (...)
     20     suppress_stderr,
     21 )
     22 from ._masked_model import MaskedModel, make_masks

File ~\miniconda3\envs\\Lib\site-packages\shap\utils\_clustering.py:7
      5 import scipy.spatial
      6 import sklearn
----> 7 from numba import njit
      9 from ._general import safe_isinstance
     10 from ._show_progress import show_progress

File ~\miniconda3\envs\\Lib\site-packages\numba\__init__.py:55
     50             msg = ("Numba requires SciPy version 1.0 or greater. Got SciPy "
     51                    f"{scipy.__version__}.")
     52             raise ImportError(msg)
---> 55 _ensure_critical_deps()
     56 # END DO NOT MOVE
     57 # ---------------------- WARNING WARNING WARNING ----------------------------
     60 from ._version import get_versions

File ~\miniconda3\envs\\Lib\site-packages\numba\__init__.py:42, in _ensure_critical_deps()
     40     raise ImportError(msg)
     41 elif numpy_version > (1, 24):
---> 42     raise ImportError("Numba needs NumPy 1.24 or less")
     43 try:
     44     import scipy

ImportError: Numba needs NumPy 1.24 or less
</details>

**Comment by connortann** [comment]
Thank you for the information. It looks like you have inconsistent numba and numpy packages installed. I don't think that's strictly speaking an issue under shap's control, so I'll remove the `bug` label from this issue for now.

You mentioned that conda had downgraded numpy to `1.24` when you installed numba, and yet you still get the issue above. So, let's debug a little, so see exactly which packages you have.

Firstly, what is the output of running `conda list` ?

Secondly, what is the output of running this python snippet?

```python
# Print out versions of the libs actually in use
import numpy as np
print(np.__file__)
print(np.__version__) 

# Check numpy version using the same logic used in numba/__init__.py
def extract_version(mod):
    return tuple(map(int, mod.__version__.split('.')[:2]))
print(extract_version(np) > (1, 24))   # Expecting `False`

# See numba version
import numba
print(numba.__file__)
print(numba.__version__)

```

**Comment by connortann** [comment]
I tried building a fresh environment with the dependencies you specified above, and cannot reproduce your issue. Conda correctly installs compatible versions of dependencies. 

```bash
# Create an environment, including shap
conda create -n shap3186 -c conda-forge python=3.11.4 jupyterlab=4.0.4 xgboost=1.7.6 scikit-learn=1.3.0 scipy pandas=2.0.3 matplotlib=3.7.2 seaborn=0.12.2 numpy shap

# Activate it
conda activate shap3186

# Show all installed versions
conda list
```

Conda correctly resolves compatible versions:

- numba 0.57.1
- numpy 1.24.4 
- shap 0.42.1

Full output of `conda list`:
<details>

```
# packages in environment at /home/connor/miniconda3/envs/shap3186:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py311hd4cff14_3    conda-forge
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotli-python             1.0.9           py311ha362b79_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h409f033_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0           py311h9547e67_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.6.8           py311hb755f60_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.2              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.42.0          py311h459d7ec_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.76.4               hfc55251_0    conda-forge
glib-tools                2.76.4               hfc55251_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.22.3               h938bd60_1    conda-forge
gstreamer                 1.22.3               h977cf35_1    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
ipykernel                 6.25.1             pyh71e2992_0    conda-forge
ipython                   8.14.0             pyh41d4057_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.0             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                4.19.0             pyhd8ed1ab_1    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.19.0             pyhd8ed1ab_1    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1           py311h38be061_0    conda-forge
jupyter_events            0.7.0              pyhd8ed1ab_2    conda-forge
jupyter_server            2.7.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.4              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.24.0             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4           py311h4dd048b_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libclang                  16.0.6          default_h1cdf331_1    conda-forge
libclang13                16.0.6          default_h4d60ac6_1    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgpg-error              1.47                 h71f35ed_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libllvm16                 16.0.6               h5cf9203_2    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.3                 hbcd7760_1    conda-forge
libsndfile                1.2.0                hb75c966_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libsystemd0               254                  h3516f8a_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxgboost                1.7.6            cpu_h6728c87_0    conda-forge
libxkbcommon              1.5.0                h5d7e998_3    conda-forge
libxml2                   2.11.5               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.40.1          py311ha6695c7_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markupsafe                2.1.3           py311h459d7ec_0    conda-forge
matplotlib                3.7.2           py311h38be061_0    conda-forge
matplotlib-base           3.7.2           py311h54ef318_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   3.0.0              pyhd8ed1ab_0    conda-forge
mpg123                    1.31.3               hcb278e6_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.33               hf1915f5_2    conda-forge
mysql-libs                8.0.33               hca2cd23_2    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.7.3              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.89                 he45b914_0    conda-forge
numba                     0.57.1          py311h96b013e_0    conda-forge
numpy                     1.24.4          py311h64a7726_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3           py311h320fe9a_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.0          py311h0b84326_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.5           py311h2582759_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulseaudio-client         16.1                 hb77b528_4    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-xgboost                1.7.6           cpu_py311hbe2e365_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py311hf0fb5b6_4    conda-forge
pyqt5-sip                 12.12.2         py311hb755f60_4    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.4          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.18.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py311hd4cff14_5    conda-forge
pyzmq                     25.1.1          py311h75c88c4_0    conda-forge
qt-main                   5.15.8              h01ceb2d_12    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.30.2             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.9.2           py311h46250e7_0    conda-forge
scikit-learn              1.3.0           py311hc009520_0    conda-forge
scipy                     1.11.1          py311h64a7726_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2              pyh41d4057_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
shap                      0.42.1          py311h320fe9a_0    conda-forge
sip                       6.7.11          py311hb755f60_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slicer                    0.0.7              pyhd8ed1ab_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0          py311h1f0f07a_1    conda-forge
terminado                 0.17.1             pyh41d4057_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py311h459d7ec_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xgboost                   1.7.6           cpu_py311hbe2e365_0    conda-forge
xkeyboard-config          2.39                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge

```

</details>

Running the python snippet above confirms that the expected versions are present, and `shap` can be imported without raising an exception.

You may have broken your environment, so I would suggest creating a new conda environment from scratch with the command above.

**Comment by SPDA36** [comment]
@connortann Thanks for the help and feedback.  I built a new environment where I installed and specified all packages in one go and `conda` resolved it correctly.  I was able to import `shap` with no dependency issues.  Thanks again for the help!

**Comment by connortann** [comment]
Glad to hear it's working for you!
