### ISSUE TITLE
Shap 0.27.0 incompatible with lightgbm 2.2.2

### ISSUE THREAD

**Issue by sei-dleung** [shap/shap#384]
when trying to call shap.TreeExplainer() with a Booster object from lightgbm, I get the following error:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'Booster' object has no attribute '_Booster__name_inner_eval'

Detailed traceback: 
  File "/Users/dleung/miniconda3/lib/python3.6/site-packages/shap/explainers/tree.py", line 91, in __init__
    self.model = TreeEnsemble(model)
  File "/Users/dleung/miniconda3/lib/python3.6/site-packages/shap/explainers/tree.py", line 491, in __init__
    self.objective = objective_name_map.get(model._Booster__name_inner_eval[0], None)
Calls: <Anonymous> -> py_call_impl
Execution halted

This issue doesn't exist when using shap 0.21.0 with lightgbm 2.2.2

**Comment by slundberg** [comment]
Thanks! That part is only need for explaining the loss function, so I wrapped it to fail silently in the new lightgbm. Later we can look for how the naming changed

**Comment by slundberg** [comment]
This should now be fixed for good on v0.28

**Comment by BlaBlaPer** [comment]
Hi @slundberg, I encountered a similar problem 'AttributeError: 'Booster' object has no attribute 'params'' when I use lightGBM version == 2.1.2 and shap version == 0.28.4. When I use shap version == 0.21.0, this problem solved~

**Comment by slundberg** [comment]
@BlaBlaPer I think that might be because of a change in LightGBM 2.2.x could you see if that fixes the issue?

**Comment by DSXiangLi** [comment]
@slundberg I am using shap 0.28.5, and lightgbm 2.2.3. I still see this error message: AttributeError: 'Booster' object has no attribute 'params'. Hasn't been fixed in 0.28.x version ?

**Comment by bbennett36** [comment]
@DSXiangLi have you figured out a solution to this?
