### ISSUE TITLE
shap.summary_plot doesn't support passing in an ax

### ISSUE THREAD

**Issue by EtienneT** [shap/shap#842]
shap.summary_plot doesn't allow to pass in an ax parameter to make the graph larger like shap.dependence_plot allows.

**Comment by slundberg** [comment]
You can just create a figure before calling summary_plot and then turn off auto resizing...but I think this should be easier so I pushed a new update to add a new "plot_size" argument.

**Comment by EtienneT** [comment]
Yep you are right, I didn't know matplotlib enough before filling this bug sorry about that.  I just did this to solve the problem locally:

fig, ax = plt.subplots(figsize=(16, 8))
shap.summary_plot(shap_values, X, auto_size_plot=False)

**Comment by JiaxiangBU** [comment]
I try it but the sub plot is overlapping still. Here is a partial solution https://github.com/slundberg/shap/issues/153#issuecomment-974783127 .

**Comment by mvanaltvorst** [comment]
Hi @slundberg ! The solution provided does not work in case one wants to create subplots. Example:

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots((len(INSTRUMENTS) + 1) // 2, 2, figsize=(12, 12))
for i, instrument in enumerate(INSTRUMENTS):
    shap.summary_plot(
        sc.shap_values[instrument],
        data[COVARIATES],
        plot_type="bar",
        show=False,
        ax = ax[i // 2, i % 2]
    )
```

Unfortunately, there is no way to get this to work without adding support for an optional axis argument.

**Comment by WillSkywalker** [comment]
Another issue I''m having is that when you try to use sharex or sharey, the labels still appear repeatedly.
