### ISSUE TITLE
Tensorflow 2.0 with SHAP

### ISSUE THREAD

**Issue by ledmaster** [shap/shap#850]
Hi,

I am getting the following error when trying to use SHAP with TF 2.

Versions: 
shap-0.30.0
tensorflow==2.0.0

type(mdl) is tensorflow.python.keras.engine.training.Model

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-212-e407a67df8af> in <module>
----> 1 e = shap.DeepExplainer(mdl, Xtrain[0,:])

~/anaconda3/lib/python3.7/site-packages/shap/explainers/deep/__init__.py in __init__(self, model, data, session, learning_phase_flags)
     78 
     79         if framework == 'tensorflow':
---> 80             self.explainer = TFDeepExplainer(model, data, session, learning_phase_flags)
     81         elif framework == 'pytorch':
     82             self.explainer = PyTorchDeepExplainer(model, data)

~/anaconda3/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py in __init__(self, model, data, session, learning_phase_flags)
    142             if self.data[0].shape[0] > 5000:
    143                 warnings.warn("You have provided over 5k background samples! For better performance consider using smaller random sample.")
--> 144             self.expected_value = self.run(self.model_output, self.model_inputs, self.data).mean(0)
    145 
    146         # find all the operations in the graph between our inputs and outputs

~/anaconda3/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py in run(self, out, model_inputs, X)
    282         """ Runs the model while also setting the learning phase flags to False.
    283         """
--> 284         feed_dict = dict(zip(model_inputs, X))
    285         for t in self.learning_phase_flags:
    286             feed_dict[t] = False

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in __hash__(self)
    711     if (Tensor._USE_EQUALITY and executing_eagerly_outside_functions() and
    712         (g is None or g._building_function)):  # pylint: disable=protected-access
--> 713       raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
    714                       "Instead, use tensor.experimental_ref() as the key.")
    715     else:

TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Comment by sondrfos** [comment]
I also have this problem, and som googling seems to stuggest that others packages using tensorflow has had the same kind of error. They were resolved by patching the package. 

To fix this temporarily until they issue a patch of SHAP I would stuggest disabeling tensorflow v2 functionality if you don't really need it. 
`tf.compat.v1.disable_v2_behavior()`

**Comment by slundberg** [comment]
The master version of SHAP now has support for TF 2.0 in GradientExplainer (not DeepExplainer yet). We get pushed in a release soon.

**Comment by tomalbrecht** [comment]
Tutorial Code (using Shap 0.31.0) with tensorflow 2.0 does not work yet.

```
# load pre-trained model and choose two images to explain
model = VGG16(weights='imagenet', include_top=True)
X,y = shap.datasets.imagenet50()
to_explain = X[[39,41]]

# load the ImageNet class names
url = "https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json"
fname = shap.datasets.cache(url)
with open(fname) as f:
    class_names = json.load(f)

# explain how the input to the 7th layer of the model explains the top two classes
def map2layer(x, layer):
    feed_dict = dict(zip([model.layers[0].input], [preprocess_input(x.copy())]))
    return K.get_session().run(model.layers[layer].input, feed_dict)
e = shap.GradientExplainer(
    (model.layers[7].input, model.layers[-1].output),
    map2layer(X, 7),
    local_smoothing=0 # std dev of smoothing noise
)
shap_values,indexes = e.shap_values(map2layer(to_explain, 7), ranked_outputs=2)

# get the names for the classes
index_names = np.vectorize(lambda x: class_names[str(x)][1])(indexes)

# plot the explanations
shap.image_plot(shap_values, to_explain, index_names)
```

```print(shap.__version__)```
'0.31.0'

**Comment by simplezhang57** [comment]
switch to "tf.compat.v1.disable_v2_behavior()" still does not work, "RuntimeError: `get_session` is not available when using TensorFlow 2.0."

**Comment by Peque** [comment]
Works for me with `tensorflow.compat.v1.disable_v2_behavior()` importing `get_session()` from `tensorflow.compat.v1.keras.backend`:

```python
import tensorflow
from tensorflow.compat.v1.keras.backend import get_session

tensorflow.compat.v1.disable_v2_behavior()
```

**Comment by dineshdaultani** [comment]
I have some dependencies on TF 2.0/TF 2.1, hence downgrading to TF 1.* breaks other pipeline. 
Is it possible to get DeepExplainer compatibility with >= TF 2.0 soon?

**Comment by Alessiobrini** [comment]
Is SHAP still incompatible with TF 2.0? I am having some issue when trying to explain my subclassed model

**Comment by clairebrekken** [comment]
Any update on DeepExplainer compatibility with TF >= 2.0?

**Comment by talipini** [comment]
Anybody has insights on when DeepExplainer for TF >2.0 will be supported? Thanks

**Comment by Djmcflush** [comment]
From my knowledge it seems to be an issue with how DeepExplainer is using graph computation. That is the issue. Just got it working by using tf.v1.keras w/ tensorflow.compat.v1.disable_v2_behavior()

**Comment by davidwanner-8451** [comment]
> From my knowledge it seems to be an issue with how DeepExplainer is using graph computation. That is the issue. Just got it working by using tf.v1.keras w/ tensorflow.compat.v1.disable_v2_behavior()

This definitely works for me, but I am a bit concerned about bouncing back and forth between versions (there some tuning features from TF2.0 that I am using, then rebuilding with specific params in TF1.0). Any idea if this is being addressed - specifically, gaining support for TF2.0 for DeepExplainer?

**Comment by msabanluc** [comment]
Are there any updates on when DeepExplainer will be compatible with TF > 2.0?

**Comment by Saranga99** [comment]
Are there any updates on when DeepExplainer will be compatible with TF > 2.0? or is there any way we can interpret LSTM models with SHAP explainers? please help to figure out compatible tf and SHAP versions

My model architecture:

Model: "sequential_2"

_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 bidirectional_6 (Bidirecti  (None, 20, 256)           152576    
 onal)                                                           
                                                                 
 bidirectional_7 (Bidirecti  (None, 20, 128)           164352    
 onal)                                                           
                                                                 
 bidirectional_8 (Bidirecti  (None, 64)                41216     
 onl)                                                           
                                                                 
 dense_6 (Dense)             (None, 30)                1950      
                                                                 
 dense_7 (Dense)             (None, 10)                310       
                                                                 
 dense_8 (Dense)             (None, 1)                 11        
                                                                 
 lambda_2 (Lambda)           (None, 1)                 0         
                                                                 
=================================================================
Total params: 360415 (1.37 MB)
Trainable params: 360415 (1.37 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

**Comment by davidwanner-8451** [comment]
@Saranga99 - I was able to just use the GradientExplainer so that I was able to keep using TF2.0. I could then use the output in tools like force plots. It took me a bit of time to wrap my head around the output when passing in a LSTM, but below is how I interpreted:

Example:
```python
print("Running Gradient Explainer")
explainer= shap.GradientExplainer(final_model, self.X_train)

# get shap values for both train and test sets
orig_feats = np.concatenate([self.X_train, self.X_test])
shap_values = explainer.shap_values(orig_feats)
print( f"Shape info: {np.array(shap_values).shape}")  # (output variable, batch number, time steps, batch variables)
```

This has worked when `final_model` is of type LSTM model.

Versions used:
```
    "shap==0.41.0",
    "keras_tuner==1.3.5",
    "protobuf==3.19.*",
    "tensorflow==2.8.2",
```

**Comment by AIHUBEI** [comment]
`import shap

# Wrap your TensorFlow model into a Keras model
def get_output_layer(model, layer_name):
    return Model(inputs=model.inputs, outputs=model.get_layer(layer_name).output)

# model_for_explainer = get_output_layer(model_with_focal_loss, 'dense_2')  # Assuming 'dense_2' is your final layer name
model_for_explainer = get_output_layer(model_with_focal_loss, "dense_2")  # Assuming 'dense_2' is your final layer name

# Load your data
sample_data = test_df.tail(6)
sample_images = sample_data['File_Path'].values

# Load and preprocess the images
sample_images_preprocessed = []
for image_path in sample_images:
    img = tf.keras.preprocessing.image.load_img(image_path, target_size=(100, 100))
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)
    sample_images_preprocessed.append(img_array)

sample_images_preprocessed = np.vstack(sample_images_preprocessed)

# Create a GradientExplainer
explainer = shap.GradientExplainer(model_for_explainer, sample_images_preprocessed)

# Calculate SHAP values
shap_values, indexes = explainer.shap_values(sample_images_preprocessed, ranked_outputs=1)

# Normalize the pixel values in the images
sample_images_preprocessed_normalized = (sample_images_preprocessed - sample_images_preprocessed.min()) / (sample_images_preprocessed.max() - sample_images_preprocessed.min())

# Plot the SHAP values with normalized images
shap.image_plot(shap_values, sample_images_preprocessed_normalized)`
