### ISSUE TITLE
Additivity check failed in TreeExplainer

### ISSUE THREAD

**Issue by knaaptime** [shap/shap#941]
Hi,

thanks for the great package. I'm getting 
` AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub. Consider retrying with the feature_dependence='independent'` 

when trying to use `shap` in our [`package`](https://github.com/pysal/tobler) (you can see the error [here](https://travis-ci.com/knaaptime/tobler/jobs/266316023)). Everything has been working fine until this week, so i'm not totally sure where to go about troubleshooting, but it looks like this bug was newly introduced. Any thoughts?

thanks again

**Comment by slundberg** [comment]
I just pushed SHAP 0.33, could you try and rerun it and see if that new version helps? You can always turn off the check by setting `check_additivity=False` in the shap_values function. But I would not recommend it since it is a new check designed to flush out any possible errors.

If 0.33 does not fix it could you share a small self-contained code snippet so I can rerun it easily to debug?

**Comment by knaaptime** [comment]
thanks for the quick response! i'll give it a shot as soon as the new version hits conda and report back

**Comment by knaaptime** [comment]
I got impatient and tested against the pypi version and this looks to be resolved. thanks!

**Comment by ShaunakSen** [comment]
Hi, I am using shap 0.34 and still getting this same error. I am using XGBoost model. Any idea why this is happening?

**Comment by benjaminvdb** [comment]
> Hi, I am using shap 0.34 and still getting this same error. I am using XGBoost model. Any idea why this is happening?

@ShaunakSen: I was running into the same issue. I just installed the latest development version from GitHub (currently at git commit `cde70feb211443cfbd9f599fcded8fe00b9d6a3d`) and this solved the problem. So you could try something like:

```
pip install git+https://github.com/slundberg/shap.git
```

**Comment by ShaunakSen** [comment]
Thanks @benjaminvdb for the reply.. I will try this

**Comment by pshirvalkar** [comment]
SHAPError: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on.   _(IT IS)_ If your data shape is correct then please report this on GitHub. _(what im doing now)_ Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was -0.000000, while the model output was 232035640548290422006620887018370987644159672324243728326724193299324051914752.000000. If this difference is acceptable you can set check_additivity=False to disable this check.

Also occurs when I use `feature_perturbation = 'tree_path_dependent'`

Using
sklearn (0.22.1) Randomforestclassifier
shap 0.35.0

**Comment by bprasad26** [comment]
I also get this error. I tried installing from the GitHub as mentioned by @benjaminvdb and run "pip install git+https://github.com/slundberg/shap.git" but still having the same issue.

**Comment by mirekphd** [comment]
Try reducing sample used for computing SHAP values, i.e. passed to `shap_values` (but keep all data for training the models to avoid deteriorating their metrics). This is how I overcame this bug (in LightGBM regressions). There seems to be a clear connection with sample size, so it could be an accumulation of rounding errors meeting a max abs diff assertion with a hard-coded limit...

**Comment by pjcimpact** [comment]
Also receiving this error on 50k samples + 50 features using latest version of the package

**Comment by zinabu-b** [comment]
ExplainerError: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. This check failed because for one of the samples the sum of the SHAP values was 0.354979, while the model output was 0.305417. If this difference is acceptable you can set check_additivity=False to disable this check.

version shap-0.41.0 slicer-0.0.7
after i made check_additivity=False still this thing coming up and i wonder if somebody help me with this
thank you
